### ISSUE TITLE
Add config file to pass input values

### ISSUE THREAD

**Issue by smarru** [softmaterialslab/nanoconfinement-md#33]
Rappture requires the input values be either sent through a config file or by stdin. Currently, the program only takes inputs as arguments. 

Enhance the input module to add in a config file option. Boost allows retaining both the command line while adding a config file as described in this tutorial -  http://www.boost.org/doc/libs/1_63_0/doc/html/program_options/tutorial.html#idp523416032

**Comment by smarru** [comment]
@kadupitiya if you haven't started on this, I found a way to work around this.

**Comment by kadupitiya** [comment]
I have done it. Just testing it now. What should I do?

**Comment by jadhao** [comment]
We have resolved this. The config file is in. And things are consistent with command line or input script

**Comment by smarru** [comment]
@kadupitiya when I run the application now it complains "can not open config file: input_config.cfg" Can you please make it so that the program can run with command line options without the cfg file? The file should be optional.

**Comment by kadupitiya** [comment]
Ok,
I will have to comment one return statement.
Currently file should be there.
Give me 5 mins.

**Comment by kadupitiya** [comment]
PS: I meant config file should be there in the place where executable is.

**Comment by jadhao** [comment]
I approved @kadupitiya fix and merged. Please check if things are fine now and this issue can be closed

**Comment by smarru** [comment]
thanks you for the quick fix, yes its good now
