### ISSUE TITLE
Production begin steps should change with time steps?

### ISSUE THREAD

**Issue by smarru** [softmaterialslab/nanoconfinement-md#38]
This could be a non-issues, started a thread to discuss it. 

Currently, it seems from the log messages that production begins always at 100000 steps. I am wondering if this should adapt to simulation time steps?

**Comment by kadupitiya** [comment]
@smarru 
Yes I think it should be. 
@jadhao what do you think about this?

**Comment by jadhao** [comment]
Yes. We can set it to a fraction of the number of total steps S. For now, lets set it to 0.1 S

**Comment by kadupitiya** [comment]
Ok.
Do you want me to map it inside the c++ program?

**Comment by jadhao** [comment]
Yes, that seems the best place for now. We can similarly adapt the density output frequency to S so that the program produces some result even for small S; it won't be very good, but at least we will have a plot.

**Comment by kadupitiya** [comment]
@jadhao 
Ok.
I will do this.

**Comment by kadupitiya** [comment]
@smarru 
I have submitted that through a new pull request.
@jadhao 
Please have a look and let me know if that is ok.
Thanks

**Comment by jadhao** [comment]
@smarru @kadupitiya I believe this has been approved. Shall we close this issue

**Comment by kadupitiya** [comment]
Yes.
I also think so.

**Comment by smarru** [comment]
Yes I verified this on nanohub as well.
