### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by jadhao** [softmaterialslab/nanoconfinement-md#43]
@smarru @kadupitiya I think now we should start documenting the manual of app development on nanohub based on what we learned from this experience. It should give the essential steps, be precise, concise, but has the details that enable other node members to realize the code-to-app transition pathway.

**Comment by smarru** [comment]
@jadhao do you have a preference on if this nanohub documentation should live within this tool or at a meta level example: softmaterialslab.github.io ?

**Comment by jadhao** [comment]
@smarru at this point, within this tool is fine; we will move it upstairs once it becomes a more general blueprint for a typical code to app transition. writing it now specific to this tool may be easier as it is fresh and the steps will flow smoothly

**Comment by smarru** [comment]
@jadhao let me know what you think of a sample documentation:
The source of it - https://github.com/smarru/nanoconfinement-md/blob/master/docs/index.md
Example link to share externally - https://smarru.github.io/nanoconfinement-md/

If you like these examples, I can send a PR to main repo and continue to add nanohub specific instructions

**Comment by jadhao** [comment]
@kadupitiya @smarru @foxsden we have the documentation; so I am closing this. the doc will remain live for future updates.
